steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.frontend', '-t', 'gcr.io/$PROJECT_ID/data-analyst-frontend', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/data-analyst-frontend']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'data-analyst-frontend'
      - '--image=gcr.io/$PROJECT_ID/data-analyst-frontend'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--set-env-vars=API_URL=https://data-analyst-backend-940502312023.us-central1.run.app'